CREATE DATABASE kakaopay;

CREATE TABLE `TBL_FLY_MONEY` (
  `FLY_MONEY_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT '뿌리기일련번호',
  `USER_ID` VARCHAR(4) NOT NULL COMMENT '사용자ID',
  `ROOM_ID` VARCHAR(4) NOT NULL COMMENT '대화방ID',
  `TOKEN` VARCHAR(3) NOT NULL COMMENT '토큰',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태 1:대기중, 2:처리중, 3:종료',
  `FLY_MONEY` INT NOT NULL COMMENT '뿌린금액',
  `LIMIT_CNT` INT NOT NULL COMMENT '제한인원',
  `LEFT_MONEY` INT NOT NULL COMMENT '남은금액',
  `LEFT_CNT` INT NOT NULL COMMENT '남은인원',
  `FLY_TIME` VARCHAR(14) NOT NULL COMMENT '뿌린시간',
  `INS_USER` VARCHAR(100) NOT NULL COMMENT '등록자',
  `INS_DATE` DATETIME NOT NULL COMMENT '등록일시',
  `UPT_USER` VARCHAR(100) DEFAULT NULL COMMENT '수정자',
  `UPT_DATE` DATETIME DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`FLY_MONEY_SEQ`,`USER_ID`,`ROOM_ID`),
  KEY `IDX1_TBL_FLY_MONEY` (`STATUS`),
  KEY `IDX2_TBL_FLY_MONEY` (`LIMIT_CNT`),
  KEY `IDX2_TBL_FLY_MONEY` (`FLY_TIME`)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE `TBL_FLY_MONEY_HIST` (
  `FLY_MONEY_HIST_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT '뿌리기이력일련번호',
  `FLY_MONEY_SEQ` INT NOT NULL COMMENT '뿌리기일련번호',
  ``kakaopay``kakaopay`` VARCHAR(4) NOT NULL COMMENT '사용자ID',
  `ROOM_ID` VARCHAR(4) NOT NULL COMMENT '대화방ID',
  `TOKEN` VARCHAR(3) NOT NULL COMMENT '토큰',
  `CATCH_USER_ID` VARCHAR(4) NOT NULL COMMENT '받은사용자ID',
  `CATCH_MONEY` INT NOT NULL COMMENT '받은금액',
  `INS_USER` VARCHAR(100) NOT NULL COMMENT '등록자',
  `INS_DATE` DATETIME NOT NULL COMMENT '등록일시',
  `UPT_USER` VARCHAR(100) DEFAULT NULL COMMENT '수정자',
  `UPT_DATE` DATETIME DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`FLY_MONEY_HIST_SEQ`,`FLY_MONEY_SEQ`,`USER_ID`,`ROOM_ID`),
  KEY `IDX1_TBL_FLY_MONEY_HIST` (`TOKEN`)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `TBL_TOKEN_MST` (
  `TKN_ID` VARCHAR(3) NOT NULL COMMENT '토큰ID',
  `USER_ID` VARCHAR(4) NOT NULL COMMENT '사용자ID',
  `PUB_TIME` CHAR(14) NOT NULL COMMENT '발급시간',
  `EXP_TIME` CHAR(14) NOT NULL COMMENT '만료시간',
  PRIMARY KEY (`TKN_ID`)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;